version: "3.9"

volumes:
  matcher-build:

services:
  matcher:
    image: matcher
    build:
      context: .
      dockerfile: Dockerfile.prod
    command:
      tail -f /dev/null
    ports:
      - '4000:4000'
    env_file:
      - .env
    volumes:
      - .:/app
      - matcher-build:/app/__build
    depends_on:
      - db
      - minio
  minio:
    image: quay.io/minio/minio:latest
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9090"
    volumes:
      - ./minio:/export
      - ./minio:/root/.minio
    ports:
      - "9000:9000"
      - "9090:9090"
  db:
    image: postgres
    env_file:
      - db/.env
    ports:
      - '5432:5432'
    volumes:
      - ./db:/docker-entrypoint-initdb.d
