version: "3.9"

services:
  db:
    image: postgres
    env_file:
      - db/.env
    ports:
      - '5432:5432'
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  pdf_gen:
    build:
      context: ./pdf_gen
      dockerfile: Dockerfile
    platform: linux/amd64
    command:
      tail -f /dev/null
    volumes:
      - ./pdf_gen:/app
    ports:
      - '3000:3000'
  minio:
    image: quay.io/minio/minio:latest
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9090"
    volumes:
      - ./minio:/export
      - ./minio:/root/.minio
    ports:
      - "9000:9000"
      - "9090:9090"
