name: Matcher build

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-matcher:
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Matcher Build, tag, and push image to Amazon ECR
        working-directory: .
        env:
          DOCKER_BUILDKIT: 1
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: matcher
          IMAGE_TAG: latest
        run: |
          docker build -f Dockerfile \
              --cache-from=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
              --build-arg BUILDKIT_INLINE_CACHE=1 \
              -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
